### ISSUE TITLE
Segfaults under OSX with conda and python 3

### ISSUE THREAD

**Issue by dpryan79** [dpryan79/pyBigWig#47]
For some unknown reason, OSX builds using python3 and conda are suddenly causing a segfault. This is breaking deepTools as well.

**Comment by dpryan79** [comment]
It turns out that this is only python 3.5. In version 3.6 everything works fine.

**Comment by dpryan79** [comment]
And only the python 3.5.4 in the default channel. The one from conda-forge works correctly. Presumably they're binary incompatible in some edge-case.

**Comment by dpryan79** [comment]
For future reference, the backtrace is as follows:

```
#0  0x00000001012808ef in PyUnicode_InternInPlace () from /Users/ryan/miniconda/lib/libpython3.5m.dylib
#1  0x000000010129066a in PyUnicode_InternFromString () from /Users/ryan/miniconda/lib/libpython3.5m.dylib
#2  0x000000010124b515 in PyType_Ready () from /Users/ryan/miniconda/lib/libpython3.5m.dylib
#3  0x000000010124b45a in PyType_Ready () from /Users/ryan/miniconda/lib/libpython3.5m.dylib
#4  0x000000010111f6d9 in PyInit_pyBigWig () from /Users/ryan/miniconda/lib/python3.5/site-packages/pyBigWig.cpython-35m-darwin.so
#5  0x000000010017f839 in _PyImport_LoadDynamicModuleWithSpec ()
#6  0x000000010017ee7c in _imp_create_dynamic ()
#7  0x000000010008777e in PyCFunction_Call ()
#8  0x000000010015056b in PyEval_EvalFrameEx ()
#9  0x00000001001495df in _PyEval_EvalCodeWithName ()
#10 0x000000010014f86b in PyEval_EvalFrameEx ()
#11 0x000000010014f61e in PyEval_EvalFrameEx ()
#12 0x000000010014f61e in PyEval_EvalFrameEx ()
#13 0x000000010014f61e in PyEval_EvalFrameEx ()
#14 0x000000010014f61e in PyEval_EvalFrameEx ()
#15 0x00000001001495df in _PyEval_EvalCodeWithName ()
#16 0x000000010005488a in function_call ()
#17 0x0000000100013132 in _PyObject_CallMethodIdObjArgs ()
#18 0x00000001001798d5 in PyImport_ImportModuleLevelObject ()
#19 0x00000001001425f5 in builtin___import__ ()
#20 0x00000001000877bf in PyCFunction_Call ()
#21 0x0000000100010d65 in PyObject_Call ()
#22 0x000000010015236a in PyEval_EvalFrameEx ()
#23 0x00000001001495df in _PyEval_EvalCodeWithName ()
#24 0x000000010019e9a5 in PyRun_StringFlags ()
#25 0x000000010019e840 in PyRun_SimpleStringFlags ()
#26 0x00000001001c005f in Py_Main ()
#27 0x0000000100001ac1 in main ()
```
